//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.NET_Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> Pages { get; set; }
        public string Price { get; set; }
        public string PriceForSale { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string IsSequel { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Id_Author { get; set; }
        public Nullable<int> Id_Genre { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
